"""ISD hourly tier: station list (WBAN-stitched, twinned to GHCN-Daily airports).

stations/isd.yaml is generated from NOAA's isd-history.csv: every US station whose
records, stitched across USAF-id changes by WBAN, span >= min_span years and are still
active. Each entry lists its (usaf, wban, first, last) id segments and its GHCN-Daily
twin (USW000<WBAN>) when that exists — day counts come from the twin's ASOS max/min;
ISD-Lite supplies the hourly layer.
"""

from __future__ import annotations

import csv
import re
from collections import defaultdict
from dataclasses import dataclass

import yaml

from climate.paths import RAW_DIR, STATIONS_DIR

ISD_META = "isd_meta"
HISTORY_URL = "https://www.ncei.noaa.gov/pub/data/noaa/isd-history.csv"
LITE_BASE = "https://www.ncei.noaa.gov/pub/data/noaa/isd-lite/"
LITE_FIRST_YEAR = 1973  # ISD-Lite is reliably hourly from 1973


@dataclass(frozen=True)
class IsdStation:
    wban: str
    name: str
    short: str
    state: str
    lat: float
    lon: float
    elev_m: float
    begin: int
    end: int
    ids: tuple[tuple[str, str, int, int], ...]  # (usaf, wban, first_year, last_year)
    ghcn: str | None = None
    tz: str = ""

    @property
    def id(self) -> str:
        return f"ISD{self.wban}"

    def usaf_for(self, year: int) -> list[str]:
        """USAF ids whose segment covers `year` (several can overlap; try each)."""
        out = [u for u, _w, a, b in self.ids if a <= year <= b]
        return out or [self.ids[-1][0]]


def _tz_for(lat: float, lon: float) -> str:
    from timezonefinder import TimezoneFinder

    return TimezoneFinder().timezone_at(lat=lat, lng=lon) or "UTC"


def generate(min_span: int = 50) -> str:
    from climate.stations import short_name

    path = RAW_DIR / ISD_META / "isd-history.csv"
    rows = [
        r
        for r in csv.DictReader(path.open(encoding="utf-8", errors="replace"))
        if r["CTRY"] == "US"
        and r["STATE"]
        and r["BEGIN"]
        and r["END"]
        and r["WBAN"] not in ("", "99999")
    ]
    ghcn = set()
    for line in (RAW_DIR / "ghcnd_meta" / "ghcnd-stations.txt").open():
        if line.startswith("USW"):
            ghcn.add(line[:11])
    by: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by[r["WBAN"]].append(r)
    from timezonefinder import TimezoneFinder

    tf = TimezoneFinder()
    entries = []
    for wban, v in by.items():
        a = min(int(x["BEGIN"][:4]) for x in v)
        b = max(int(x["END"][:4]) for x in v)
        if b < 2025 or b - a < min_span - 1:
            continue
        latest = max(v, key=lambda x: x["END"])
        try:
            lat, lon = float(latest["LAT"]), float(latest["LON"])
        except ValueError:
            continue
        ids = sorted({(x["USAF"], x["WBAN"], int(x["BEGIN"][:4]), int(x["END"][:4])) for x in v})
        gid = f"USW000{wban}"
        name = re.sub(r"\s+", " ", latest["STATION NAME"]).strip()
        entries.append(
            {
                "wban": wban,
                "name": name,
                "short": short_name(name.replace("/", " ")),
                "state": latest["STATE"],
                "lat": lat,
                "lon": lon,
                "elev_m": float(latest["ELEV(M)"] or 0),
                "begin": a,
                "end": b,
                "ids": [list(i) for i in ids],
                "ghcn": gid if gid in ghcn else None,
                "tz": tf.timezone_at(lat=lat, lng=lon) or "UTC",
            }
        )
    entries.sort(key=lambda e: (e["state"], e["name"]))
    doc = {
        "tier": "isd",
        "name": "Hourly airport observations (ISD)",
        "min_span": min_span,
        "lite_first_year": LITE_FIRST_YEAR,
        "stations": entries,
    }
    head = (
        "# Generated by `clim stations --tier isd`: US ISD stations active in 2025 whose\n"
        f"# WBAN-stitched records span >= {min_span} years ({len(entries)} stations). Regenerate\n"
        "# rather than edit. `ghcn` is the co-located GHCN-Daily airport record.\n"
    )
    return head + yaml.safe_dump(doc, sort_keys=False, width=200)


def write_isd_list(min_span: int = 50) -> int:
    text = generate(min_span)
    (STATIONS_DIR / "isd.yaml").write_text(text)
    return text.count("\n- wban:") + text.count("\n  - wban:")


def load_isd_stations(only: list[str] | None = None) -> list[IsdStation]:
    p = STATIONS_DIR / "isd.yaml"
    if not p.exists():
        return []
    doc = yaml.safe_load(p.read_text())
    out = []
    for e in doc["stations"]:
        st = IsdStation(
            wban=str(e["wban"]),
            name=e["name"],
            short=e["short"],
            state=e["state"],
            lat=float(e["lat"]),
            lon=float(e["lon"]),
            elev_m=float(e["elev_m"]),
            begin=int(e["begin"]),
            end=int(e["end"]),
            ids=tuple((str(i[0]), str(i[1]), int(i[2]), int(i[3])) for i in e["ids"]),
            ghcn=e.get("ghcn"),
            tz=e.get("tz", "UTC"),
        )
        if only is None or st.wban in only or st.id in only or (st.ghcn and st.ghcn in only):
            out.append(st)
    return out
