"""Generate a region file from NOAA's inventory: every US station whose TMAX and TMIN
records span at least `min_span` years. Completeness is judged later (after ingest)
by `clim check`; this is the candidate list to download."""

from __future__ import annotations

import re

import polars as pl

from climate.ingest.store import load_inventory, load_stations
from climate.paths import STATIONS_DIR

ABBREV = {
    "AP": "Airport",
    "INTL": "International",
    "MUNI": "Municipal",
    "RGNL": "Regional",
    "FLD": "Field",
    "AFB": "AFB",
    "NAS": "NAS",
    "MCAS": "MCAS",
    "RS": "Ranger Station",
    "RNG": "Ranger",
    "STN": "Station",
    "EXP": "Experiment",
    "EXPT": "Experiment",
    "PWR": "Power",
    "PLT": "Plant",
    "RSVR": "Reservoir",
    "DAM": "Dam",
    "FC": "",
    "WB": "",
    "CO": "County",
    "CTR": "Center",
    "UNIV": "University",
    "AGR": "Agricultural",
    "AG": "Ag.",
    "NR": "near",
    "MT": "Mt.",
    "MTN": "Mountain",
    "PK": "Peak",
    "LK": "Lake",
    "SPGS": "Springs",
    "SPG": "Spring",
    "JCT": "Junction",
    "HTS": "Heights",
    "FT": "Fort",
    "ST": "St.",
    "PT": "Point",
    "PSA": "",
}


KEEP_UPPER = {
    "NAS",
    "AFB",
    "MCAS",
    "MCAF",
    "NWS",
    "USC",
    "UCLA",
    "LAX",
    "AAF",
    "NAF",
    "USGS",
    "WSO",
    "WSFO",
    "FAA",
    "NPS",
    "TVA",
    "KOA",
    "NE",
    "NW",
    "SE",
    "SW",
    "N",
    "S",
    "E",
    "W",
    "II",
    "III",
    "SR",
    "JR",
}


def short_name(noaa: str) -> str:
    words = []
    for w in noaa.split():
        if re.fullmatch(r"\d+[NSEW]{1,3}", w):  # "4.4 WNW" style offsets
            words.append(w)
            continue
        if w in ABBREV:
            if ABBREV[w]:
                words.append(ABBREV[w])
            continue
        if re.fullmatch(r"[A-Z]{1,4}", w) and w in KEEP_UPPER:
            words.append(w)
        else:
            words.append(w.title())
    return " ".join(words)


def generate(region_id: str, name: str, min_span: int, exclude: set[str]) -> str:
    stations = load_stations().filter(pl.col("id").str.starts_with("US"))
    inv = load_inventory().filter(pl.col("element").is_in(["TMAX", "TMIN"]))
    span = (
        inv.group_by("id")
        .agg(
            pl.col("first_year").max().alias("first"),
            pl.col("last_year").min().alias("last"),
            pl.len().alias("n"),
        )
        .filter((pl.col("n") == 2) & ((pl.col("last") - pl.col("first")) >= min_span - 1))
    )
    df = (
        stations.join(span, on="id")
        .filter(pl.col("state") != "")
        .filter(~pl.col("id").is_in(list(exclude)))
        .sort(["state", "name"])
    )
    lines = [
        "# Generated by `clim stations`: every US station with TMAX and TMIN spanning",
        f"# >= {min_span} years in ghcnd-inventory.txt ({df.height} stations). Completeness is",
        "# judged after ingest. Regenerate rather than edit.",
        f"region: {region_id}",
        f"name: {name}",
        "generated: true",
        "center: [39.5, -98.0]",
        "zoom: 3.6",
        "default_station: USC00046719",
        "stations:",
    ]
    for r in df.iter_rows(named=True):
        lines.append(
            f"  - {{id: {r['id']}, short: {_yaml(short_name(r['name']))}, state: {r['state']}}}"
        )
    return "\n".join(lines) + "\n"


def _yaml(s: str) -> str:
    return '"' + s.replace('"', "'") + '"'


def write_region(region_id: str = "us", min_span: int = 50) -> int:
    from climate.config import load_regions

    exclude = {e.id for reg in load_regions() for e in reg.excluded}
    text = generate(region_id, "United States", min_span, exclude)
    (STATIONS_DIR / f"{region_id}.yaml").write_text(text)
    return text.count("\n  - {id:")
